---
title: "Assignment3"
author: "Lars Mehwald and Daniel Salgado Moreno"
date: "13 November 2015"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Regression analysis 

```{r plot, echo=FALSE, results='asis', warning=FALSE, message=FALSE}

# It is important to add asis in order for markdown to compile the document 
# If cache is added then it is not re-run, even if file changes
# Info on options: http://yihui.name/knitr/options/

# source("DataAnalysis.R")

```

```{r SummaryStatistics, echo=FALSE, results='asis', warning=FALSE, message=FALSE}
# Setting the working directory
library("repmis")
library("stargazer")
possible_dir <- c('D:/Eigene Dokumente/!1 Vorlesungen/!! WS 2015/Introduction to Collaborative Social Science Data Analysis/Assignment3', 
                  '~/HSoG/DataAnalysis/GitHub/Assignment3')
set_valid_wd(possible_dir)
rm(possible_dir)
# Loading data set from csv file
DistrictData <- read.csv(file="Analysis/data/DistrictData2013.csv")
# Removing ranking column (it was added in the saving process in DataMerging.R)
DistrictData <- DistrictData[,-1]
# Removing some variables
DistrictDataReduced <- DistrictData[,c(22,40,47,49,50,51,52,53,55,57,59)]
# Creation of summary statistics
stargazer(DistrictDataReduced)
```
